/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:89c5a0c1-af76-4937-95c2-00c19389b67a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rvoOmRivs",
    "aws_user_pools_web_client_id": "3bh84jkvn341nvi3lkcnp5c2m2",
    "oauth": {}
};


export default awsmobile;
